import type { Metadata } from "next";
import Link from "next/link";
import { ContentPage, ContentSection } from "@/components/common/ContentPage";
import { buildMetadata } from "@/lib/seo/metadata";

export const metadata: Metadata = buildMetadata({
  title: "Data sources",
  description: "Where ScholarTrack's catalogue data comes from and how it gets in.",
  path: "/data-sources",
});

export default function DataSourcesPage() {
  return (
    <ContentPage title="Data sources" lastReviewed="Last reviewed for Checkpoint 6.">
      <ContentSection heading="Official sources only">
        <p>
          Every catalogue record links to (or names) an official source — the government agency, university,
          foundation, or company actually running the programme. ScholarTrack does not accept a record without one:
          publishing without a linked official source is rejected at the database level, not just by convention.
        </p>
      </ContentSection>

      <ContentSection heading="How a record enters the catalogue">
        <p>
          Staff enter records individually through a reviewed workflow, or in bulk through a CSV import tool with its
          own validation (file size and row limits, an allowed-column list, and duplicate detection against existing
          records). Either path goes through the same draft → review → approve → publish pipeline before anything is
          public.
        </p>
      </ContentSection>

      <ContentSection heading="No AI-generated or scraped catalogue facts">
        <p>
          Catalogue facts (deadlines, funding, eligibility, required documents) are entered and reviewed by staff —
          never generated by a language model, and never scraped automatically from a third-party site without human
          review. The optional AI assistant answers <em>from</em> this staff-curated data; it does not add new facts
          to it.
        </p>
      </ContentSection>

      <ContentSection heading="Keeping data current">
        <p>
          Staff periodically re-check published records against their official source and update the &ldquo;last
          checked&rdquo; date and verification status accordingly. Anyone can flag a record that looks stale or wrong
          using the &ldquo;Report incorrect information&rdquo; button on its detail page. See{" "}
          <Link href="/verification-policy" className="underline">
            Verification policy
          </Link>{" "}
          for what each status means.
        </p>
      </ContentSection>
    </ContentPage>
  );
}
