-- Hand-authored migration (not generated by `drizzle-kit generate`).
--
-- Provides the SQL-level building blocks the RLS policies in the generated
-- schema migration (0001_*) depend on:
--   1. The `anon` / `authenticated` / `service_role` Postgres roles. A real
--      Supabase project already creates these; this migration creates them
--      defensively with existence guards so it is also safe to run against a
--      plain local Postgres container (see scripts/db/local-auth-shim.sql for
--      the additional `auth.uid()` stub needed ONLY for local testing).
--   2. `app.is_staff(uid, roles)`, the single SECURITY DEFINER function every
--      staff-facing RLS policy calls, so "what counts as staff" lives in one
--      place.
--   3. `app.reject_mutation()`, a trigger function used by 0002 to make
--      audit_log append-only at the database level (defined here; attached
--      to the table in 0002 once the table exists).

do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'anon') then
    create role anon nologin noinherit;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'authenticated') then
    create role authenticated nologin noinherit;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'service_role') then
    create role service_role nologin noinherit bypassrls;
  end if;
end
$$;

create schema if not exists app;

-- `roles` is NULL to mean "any active staff role assignment". Otherwise the
-- caller must hold an active (non-revoked) assignment for one of the given
-- roles. SECURITY DEFINER so `anon`/`authenticated` callers (who cannot read
-- staff_role_assignments directly under RLS) can still have this predicate
-- evaluated inside their own policies.
--
-- `language plpgsql` (not `sql`) is deliberate: a `language sql` function
-- body is parsed and bound against real catalog objects at CREATE FUNCTION
-- time, but staff_role_assignments/staff_profiles do not exist yet this
-- early in the migration sequence (0001 creates them). plpgsql bodies are
-- only syntax-checked at creation time and resolved at call time, so this
-- migration can run before 0001 while 0001's CREATE POLICY statements (which
-- must be able to resolve app.is_staff already) still succeed.
create or replace function app.is_staff(caller_id uuid, roles text[])
returns boolean
language plpgsql
security definer
set search_path = public
stable
as $$
begin
  return exists (
    select 1
    from staff_role_assignments sra
    join staff_profiles sp on sp.id = sra.staff_profile_id
    where sra.staff_profile_id = caller_id
      and sra.revoked_at is null
      and sp.status = 'active'
      and (roles is null or sra.role::text = any(roles))
  );
end;
$$;

revoke all on function app.is_staff(uuid, text[]) from public;
grant execute on function app.is_staff(uuid, text[]) to anon, authenticated, service_role;

-- Generic "reject this mutation" trigger function, attached to audit_log's
-- UPDATE/DELETE triggers in 0002 once that table exists.
create or replace function app.reject_mutation()
returns trigger
language plpgsql
as $$
begin
  raise exception '% on % is not permitted: this table is append-only', tg_op, tg_table_name;
end;
$$;
